### ISSUE TITLE
Can we hide https:// ?

### ISSUE THREAD

**Issue by adrianvintu** [developerjamiu/smart-text-flutter#10]
Is there a possibility to hide "https://" in "https://google.com"?

Like here https://github.com/Gaurav-CareMonitor/linkify_plus

```
By default, humanization (removal of http:// or https:// from the start of the URL) is enabled. You may disable it by passing options:

Linkify(
  text: "Made by https://cretezy.com",
  options: LinkifyOptions(humanize: false),
);

```

**Comment by developerjamiu** [comment]
This is implemented on this [PR](https://github.com/developerjamiu/smart-text-flutter/pull/14). It should be available on the next release.

**Comment by developerjamiu** [comment]
Closing this as the fix has been [published](https://pub.dev/packages/smart_text_flutter). Feel free to re-open if you get the issue still.

Please note that humanize is false by default. You can however set humanize to true to remove the https or http
