### ISSUE TITLE
Cn we disable parsing for email, date, etc?

### ISSUE THREAD

**Issue by adrianvintu** [developerjamiu/smart-text-flutter#11]
I only need the users to visibly see the links as underlined. I do not want special handling for email, telephone, etc.

Is there a way to not parse email, tel, etc?

**Comment by kiddo4** [comment]
you could use thier configs to edit the styling

**Comment by adrianvintu** [comment]
I am using this instead https://github.com/knoxpo/flutter_smart_text_view/blob/master/lib/smart_text_view.dart

smart-text-flutter crashed on ios - parsing range error https://github.com/developerjamiu/smart-text-flutter/issues/12

**Comment by developerjamiu** [comment]
Apologies for the late response and action. This issue is fixed in this [PR](https://github.com/developerjamiu/smart-text-flutter/pull/13) and will be available in the next release.
