### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by adrianvintu** [developerjamiu/smart-text-flutter#12]
The whole app crashes for the following text

"bine ai venit Emilia!\r\n\r\nin primul rand ai activitatile din Gestioneaza emotiile, iar apoi programul\r\n\r\ndaca doresti, faci update la aplicatie pentru versiunea noau de azi, aici \r\nhttps://play.google.com/store/apps/details?id=stop_anxietate.ro"

<img width="1728" alt="Screenshot 2024-10-21 at 23 02 25" src="https://github.com/user-attachments/assets/fa9a6b95-5c7e-46ad-8521-19e3b2d85827">
<img width="1728" alt="Screenshot 2024-10-21 at 23 02 37" src="https://github.com/user-attachments/assets/5bdbd344-f917-4ab2-b609-f273fc473576">
<img width="1728" alt="Screenshot 2024-10-21 at 23 02 37" src="https://github.com/user-attachments/assets/38855e71-d414-471c-9330-b57070a8f9c7">

smart_text_flutter: ^0.3.1

**Comment by developerjamiu** [comment]
Apologies for the late response and action. This issue is fixed in this [PR](https://github.com/developerjamiu/smart-text-flutter/pull/13) and will be available in the next release.

**Comment by developerjamiu** [comment]
Closing this as the fix has been [published](https://pub.dev/packages/smart_text_flutter). Feel free to re-open if you get the issue still.

**Comment by itsatishay** [comment]
🦏 🔵 for tonight 

The above text is crashing the app
